version: '3.9'

services:
  minio:
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin1234
    image: quay.io/minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"

  mysqldb:
    image: mysql:8
    ports:
      - "3306:3306"
    networks:
      - discord
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=root

  discord-app:
    build: backend
    ports:
      - "6060:6060"
    networks:
      - discord
    depends_on:
      - mysqldb

  frontend:
    build: frontend
    ports:
      - "4200:4200"
    networks:
      - discord
    depends_on:
      - discord-app

networks:
  discord: