version: '3.9'

services:
  minio:
    container_name: Minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin1234
    image: quay.io/minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"

  mysqldb:
    image: mysql:8
    networks:
      - discord
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=root

  discord-app:
    build: .
    ports:
      - "6060:6060"
    networks:
      - discord
    depends_on:
      - mysqldb

networks:
  discord: