server:
  port: 6060

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: discord.clone.app@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
