server:
  port: 6060

minio:
  user: admin
  password: admin1234
  url: http://localhost:9000

frontend-url: "https://frontend-production-47b5.up.railway.app"

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: discord.clone.app@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
  config:
    import: optional:secrets.yaml
