name: Backend CI/CD

on:
  push:
    paths: [ "backend/**" ]
    
defaults:
 run:
  working-directory: backend

jobs:

  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
  
  CD:
    needs: CI
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    - name: Install Railway
      run: npm i -g @railway/cli
    - name: Deploy
      run: railway up --service=backend -d
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    
